<?php
$this->breadcrumbs=array(
	'Dims'=>array('index'),
	$model->NIM,
);

$this->menu=array(
array('label'=>'List Dim','url'=>array('index')),
array('label'=>'Create Dim','url'=>array('create')),
array('label'=>'Update Dim','url'=>array('update','id'=>$model->NIM)),
array('label'=>'Delete Dim','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->NIM),'confirm'=>'Are you sure you want to delete this item?')),
array('label'=>'Manage Dim','url'=>array('admin')),
);
?>

<h1>View Dim #<?php echo $model->NIM; ?></h1>

<?php $this->widget('booster.widgets.TbDetailView',array(
'data'=>$model,
'attributes'=>array(
		'NIM',
		'NO_USM',
		'JALUR',
		'USER_NAME',
		'KBK_ID',
		'KPT_PRODI',
		'ID_KUR',
		'NAMA',
		'TGL_LAHIR',
		'TEMPAT_LAHIR',
		'GOL_DARAH',
		'JENIS_KELAMIN',
		'AGAMA',
		'ALAMAT',
		'KABUPATEN',
		'KODE_POS',
		'EMAIL',
		'TELEPON',
		'HP',
		'HP2',
		'NAMA_SMA',
		'NO_IJAZAH_SMA',
		'ALAMAT_SMA',
		'KABUPATEN_SMA',
		'KODEPOS_SMA',
		'TELEPON_SMA',
		'THN_MASUK',
		'STATUS_AKHIR',
		'NAMA_AYAH',
		'NAMA_IBU',
		'NO_HP_AYAH',
		'NO_HP_IBU',
		'ALAMAT_ORANGTUA',
		'PEKERJAAN_AYAH',
		'KETERANGAN_PEKERJAAN_AYAH',
		'PENGHASILAN_AYAH',
		'PEKERJAAN_IBU',
		'KETERANGAN_PEKERJAAN_IBU',
		'PENGHASILAN_IBU',
		'NAMA_WALI',
		'PEKERJAAN_WALI',
		'KETERANGAN_PEKERJAAN_WALI',
		'PENGHASILAN_WALI',
		'ALAMAT_WALI',
		'TELEPON_WALI',
		'NO_HP_WALI',
		'PENDAPATAN',
		'IPK',
		'ANAK_KE',
		'DARI_JLH_ANAK',
		'JUMLAH_TANGGUNGAN',
		'NILAI_USM',
		'SCORE_IQ',
		'REKOMENDASI_PSIKOTEST',
		'LAST_UPDATE',
		'USER_ID',
		'WS',
),
)); ?>
