<H1>Choose your Detail Date</h1>
<TABLE>
    <TR>
        <TD>
            <?php
          $this->widget('ext.simple-calendar.SimpleCalendarWidget');
            ?>
        </TD>
        <TD>
        </TD>
        <TD>
        </TD>
        <TD>
        </TD>
        <TD>
        </TD>
        <TD>
        </TD>
        <TD>
        </TD>
        <TD>
        </TD>
        <TD>
        </TD>
        <TD>
        </TD>
        <TD>
        </TD>
        <TD>
        </TD>
        <TD>
        </TD>
        <TD>
        </TD>
        
    <TR>
</TABLE>
